language: rust
sudo: false
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      env:
       - FEATURES='test_low_transition_point test'
branches:
  only:
    - master
    - rebel
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      cargo test --release --verbose --features "$FEATURES" &&
      cargo doc --verbose --features "$FEATURES"
